#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again. This script gets executed directly, so it could be python, php,
# ruby, etc.

# Activate virtual environment
source $VIRTUAL_ENV/bin/activate

# Prepare necessary persistent data folders
if [ ! -d $OPENSHIFT_DATA_DIR/wagtail-openshift-quickstart-local ]; then
    mkdir $OPENSHIFT_DATA_DIR/wagtail-openshift-quickstart-local
fi

if [ ! -d $OPENSHIFT_DATA_DIR/wagtail-openshift-quickstart-local/conf ]; then
    mkdir $OPENSHIFT_DATA_DIR/wagtail-openshift-quickstart-local/conf
fi

if [ ! -d $OPENSHIFT_DATA_DIR/wagtail-openshift-quickstart-local/logs ]; then
    mkdir $OPENSHIFT_DATA_DIR/wagtail-openshift-quickstart-local/logs
fi

if [ ! -d $OPENSHIFT_DATA_DIR/wagtail-openshift-quickstart-local/media ]; then
    mkdir $OPENSHIFT_DATA_DIR/wagtail-openshift-quickstart-local/media
fi

# Prepare default local_settings.py
if [ ! -f $OPENSHIFT_DATA_DIR/wagtail-openshift-quickstart-local/conf/local_settings.py ]; then
    cp $OPENSHIFT_REPO_DIR/data/local_settings.py $OPENSHIFT_DATA_DIR/wagtail-openshift-quickstart-local/conf/local_settings.py
fi

# Executing migrate (database sync)
python "$OPENSHIFT_REPO_DIR"wsgi/wagtail-openshift-quickstart/manage.py migrate --noinput

# Executing collectstatic (organize static files)
python "$OPENSHIFT_REPO_DIR"wsgi/wagtail-openshift-quickstart/manage.py collectstatic --noinput

# Link the persistent media folder from inside the repo to enable media serving
if [ -d $OPENSHIFT_REPO_DIR/wsgi/static/media ]; then
    ln -sf $OPENSHIFT_DATA_DIR/wagtail-openshift-quickstart-local/media $OPENSHIFT_REPO_DIR/wsgi/static/media
fi
