#!/usr/bin/python
import os
import sys

# Necessary local variables
virtenv = os.path.join(os.environ['OPENSHIFT_PYTHON_DIR'], 'virtenv')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

# Necessary environment variables
os.environ['DJANGO_SETTINGS_MODULE'] = 'backcore.settings'
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'xperience'))
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python3.3/site-packages')

# Activate own virtual environment
try:
    with open(virtualenv) as f:
        exec(f.read(), dict(__file__=virtualenv))
    
except IOError:
    pass

# Starting django wsgi handler
from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()

